# School-specific overrides for the shared app.
# Copy this file to another repo and keep the same structure when you need to customize colors, logos, APIs, etc.
school_config <- list(
  team_code = "PCU",
  # Player filters
  allowed_pitchers = c(
  "Stoller, Cody",
  "Levine, Will",
  "Shreve, Ryan",
  "DeVries, Jadon",
  "Barnes, Jon",
  "Giles, Ken",
  "Dillard, Trey",
  "Raquet, Nick",
  "Kenyon, TJ",
  "Cohen, Chase",
  "Thompson, Clay",
  "Damme, Andrew",
  "Misiaszek, Andrew",
  "Valenzuela, Jesse",
  "Jackson, Logan",
  "Hawks, Ryan",
  "Colwell, Cooper",
  "Beelek, Ryan",
  "Gomez, Rio",
  "Lachot, Sam",
  "Hale, Derek",
  "Gessner, Josh",
  "Conley, Bryce",
  "Game, Gaynor",
  "Game, Halverson",
  "Game, Chipman",
  "Racioppo, Frank",
  "Silverio, Joseph",
  "Wells, Cameron",
  "Barker, Trey",
  "Blanco, Adrian",
  "Nichols, Logan",
  "Tseng, Andrew",
  "Wallace, Ren",
  "Burnett, Hudson",
  "Siebenbrodt, Jack",
  "Bentivolio, Matt",
  "Coleman, Brayden",
  "Anderson, Kade",
  "McGinnis, Ayden",
  "Halverson, Ayden",
  "Chipman, Jay",
  "Sampson, Adrian",
  "Day, Dawson",
  "Ciuffetelli, Christian",
  "Golnik, Alex",
  "Jones, Trevor",
  "Holmes, Ben",
  "Carr, Bradley",
  "Good, Colson",
  "Garza, Justin",
  "Gaynor, Jared",
  "Kriske, Brooks",
  "Davis, Austin",
  "Kalish, Jake",
  "Cody, Kyle",
  "Lujan, Van",
  "Lile, Chase",
  "Hansen, Tyler",
  "Cleavinger, Garrett",
  "Rasmussen, Drew",
  "Howard, Spencer",
  "Woo, Bryan",
  "Cusick, Ryan",
  "Shuster, Jared",
  "Fleming, William",
  "Pascanu, Tommy",
  "Dunn, Dallas",
  "Ruiz, Rene",
  "Jacobs, Andrew",
  "Headon, Grayson",
  "Nelms, Jake",
  "Kao, Ryan",
  "Jameson, Caleb",
  "Smith, Matt",
  "Lavine, Justin",
  "Fleck, Cam",
  "Fleck, Jax",
  "Wheeler, Owen",
  "Robinett, Caden",
  "Bowman, Brock",
  "McDonald, Gaven",
  "Pringle, Noah",
  "Gorder, Tyson",
  "Darnell, Noah",
  "Dilger, Ryan",
  "Haworth, Aidan",
  "Daniels, Tate",
  "Mogen, Cristian",
  "Wheeler, Henry",
  "Hargrave, Jonah",
  "Theile, Garrett",
  "Daniels, Tyke",
  "Licardi, Matt",
  "Wright, Talan",
  "Daly, Grant",
  "Madison, Bryce",
  "Camas, Ryan",
  "Wolfley, Wes",
  "Del Rio, Micah",
  "Newkirk, Hunter",
  "Stegon, Nick",
  "Martino, Mason",
  "Golnik, Alex",
  "Alberts, Andrew",
  "Duval, Trevin",
  "Foster, Brady",
  "Burnes, Corbin",
  "Taylor, Curtis",
  "Rigby, Gavin",
  "Hahn, Jesse",
  "Wetzler, Jaxon",
  "Hader, Josh",
  "Bruihl, Justin",
  "Gessner, Josh",
  "Gaynor, Sidearm",
  "Miller, Shelby",
  "Skubal, Tarik",
  "Saucedo, Taylor",
  "Knight, Tyler",
  "Zuber, Tyler",
  "Quattrocchi, Anthony" 
    
  ),
  allowed_hitters = c(
    "Stoller, Cody",
  "Barnes, Jon",
  "Giles, Ken",
  "Dillard, Trey",
  "Raquet, Nick",
  "Kenyon, TJ",
  "Cohen, Chase",
  "Thompson, Clay",
  "Damme, Andrew",
  "Misiaszek, Andrew",
  "Valenzuela, Jesse",
  "Jackson, Logan",
  "Hawks, Ryan",
  "Colwell, Cooper",
  "Beelek, Ryan",
  "Gomez, Rio",
  "Lachot, Sam",
  "Hale, Derek",
  "Gessner, Josh",
  "Conley, Bryce",
  "Game, Gaynor",
  "Game, Halverson",
  "Game, Chipman",
  "Racioppo, Frank",
  "Silverio, Joseph",
  "Wells, Cameron",
  "Barker, Trey",
  "Blanco, Adrian",
  "Nichols, Logan",
  "Tseng, Andrew",
  "Wallace, Ren",
  "Burnett, Hudson",
  "Siebenbrodt, Jack",
  "Bentivolio, Matt",
  "Coleman, Brayden",
  "Anderson, Kade",
  "McGinnis, Ayden",
  "Halverson, Ayden",
  "Chipman, Jay",
  "Sampson, Adrian",
  "Day, Dawson",
  "Ciuffetelli, Christian",
  "Golnik, Alex",
  "Jones, Trevor",
  "Holmes, Ben",
  "Carr, Bradley",
  "Good, Colson",
  "Garza, Justin",
  "Gaynor, Jared",
  "Kriske, Brooks",
  "Davis, Austin",
  "Kalish, Jake",
  "Cody, Kyle",
  "Lujan, Van",
  "Lile, Chase",
  "Hansen, Tyler",
  "Cleavinger, Garrett",
  "Rasmussen, Drew",
  "Howard, Spencer",
  "Woo, Bryan",
  "Cusick, Ryan",
  "Shuster, Jared",
  "Fleming, William",
  "Pascanu, Tommy",
  "Dunn, Dallas",
  "Ruiz, Rene",
  "Jacobs, Andrew",
  "Headon, Grayson",
  "Nelms, Jake",
  "Kao, Ryan",
  "Jameson, Caleb",
  "Smith, Matt",
  "Lavine, Justin",
  "Fleck, Cam",
  "Fleck, Jax",
  "Wheeler, Owen",
  "Robinett, Caden",
  "Bowman, Brock",
  "McDonald, Gaven",
  "Pringle, Noah",
  "Gorder, Tyson",
  "Darnell, Noah",
  "Dilger, Ryan",
  "Haworth, Aidan",
  "Daniels, Tate",
  "Mogen, Cristian",
  "Wheeler, Henry",
  "Hargrave, Jonah",
  "Theile, Garrett",
  "Daniels, Tyke",
  "Licardi, Matt",
  "Wright, Talan",
  "Daly, Grant",
  "Madison, Bryce",
  "Camas, Ryan",
  "Wolfley, Wes",
  "Del Rio, Micah",
  "Newkirk, Hunter",
  "Stegon, Nick",
  "Martino, Mason",
  "Golnik, Alex",
  "Alberts, Andrew",
  "Duval, Trevin",
  "Foster, Brady",
  "Burnes, Corbin",
  "Taylor, Curtis",
  "Rigby, Gavin",
  "Hahn, Jesse",
  "Wetzler, Jaxon",
  "Hader, Josh",
  "Bruihl, Justin",
  "Gessner, Josh",
  "Gaynor, Sidearm",
  "Miller, Shelby",
  "Skubal, Tarik",
  "Saucedo, Taylor",
  "Knight, Tyler",
  "Zuber, Tyler",
  "Quattrocchi, Anthony" 
  ),
  allowed_campers = character(0),
  colors = list(
    primary             = "#000000",   # logo black
    accent              = "#d71920",   # logo red
    accent_secondary    = "#8f0f14",   # darker red for gradients/states
    background          = "#f4f4f4",   # neutral light background
    background_secondary= "#e5e5e5"    # neutral secondary background

  ),
  logo = "PCUlogo.png",
  # Optional: Custom Reports page only (light mode + light PDF) alternate right-side logo.
  # If omitted or file is missing in /www, app automatically falls back to `logo`.
  custom_reports_light_logo = "GCUpurplelogo.png",
  coaches_emails = c(
    "ahalverson@pitchingcoachu.com",
    "jchipman@pitchingcoachu.com",
    "jgaynor@pitchingcoachu.com"
  ),
  notes_api = list(
    base_url = "https://script.google.com/macros/s/AKfycbwl9Xfu3N6GtEw8WvOpvgwNx7S3XVR4VDKKmFbRfJtBI3nZWuoFmYk3nNF9oQ682dOX1w/exec",
    token = "pcubaseball"
  ),
  extra = list(
    school_name = "PCU",
    ftp_folder = "trackman",
    cloudinary_folder = "trackman"
  )
)

colorize_css <- function(css, accent, accent_secondary, background, background_secondary) {
  accent_rgb <- paste(grDevices::col2rgb(accent), collapse = ",")
  accent_secondary_rgb <- paste(grDevices::col2rgb(accent_secondary), collapse = ",")
  css <- gsub("#e35205", accent, css, fixed = TRUE)
  css <- gsub("#ff8c1a", accent_secondary, css, fixed = TRUE)
  css <- gsub("rgba(227,82,5", paste0("rgba(", accent_rgb), css, fixed = TRUE)
  css <- gsub("rgba(227, 82, 5", paste0("rgba(", accent_rgb), css, fixed = TRUE)
  css <- gsub("rgba(255,140,26", paste0("rgba(", accent_secondary_rgb), css, fixed = TRUE)
  css <- gsub("rgba(255, 140, 26", paste0("rgba(", accent_secondary_rgb), css, fixed = TRUE)
  css <- gsub("#f5f7fa", background, css, fixed = TRUE)
  css <- gsub("#e8ecf1", background_secondary, css, fixed = TRUE)
  css
}
