import { NextResponse } from 'next/server';
import { requireAiAccess } from '../../../../../lib/ai-access';
import { claimFlagNotification, listFlagRules } from '../../../../../lib/ai-workspace-db';
import { evaluateFlagRules } from '../../../../../lib/flag-evaluation';
import { createNotificationsForUsers } from '../../../../../lib/training-db';
import { sendPushNotificationToUsers } from '../../../../../lib/push-notifications';
export const maxDuration=300;
function ymd(date:Date){return date.toISOString().slice(0,10);}
export async function GET(request:Request){const a=await requireAiAccess(request,true);if(!a.ok)return NextResponse.json({error:a.error},{status:a.status});const rules=await listFlagRules(a.organizationId);if(!rules.some((r)=>r.enabled))return NextResponse.json({results:[],rules});const maxDays=Math.max(...rules.map((r)=>r.baselineDays),30)+45;const start=new Date();start.setUTCDate(start.getUTCDate()-maxDays);const end=new Date();const origin=new URL(request.url).origin;const headers:Record<string,string>={cookie:request.headers.get('cookie')??''};const auth=request.headers.get('authorization');if(auth)headers.authorization=auth;const fetchDomain=async(domain:'pitching'|'hitting')=>{if(!rules.some((r)=>r.enabled&&r.domain===domain))return [] as Array<Record<string,unknown>>;const url=new URL(`/api/dashboard/${domain}/overview`,origin);url.searchParams.set('start_date',ymd(start));url.searchParams.set('end_date',ymd(end));url.searchParams.set('include_chart_points','1');url.searchParams.set('chart_only','1');url.searchParams.set('table_mode','Custom');url.searchParams.set('split_by',domain==='pitching'?'Pitcher':'Batter');const response=await fetch(url,{headers,cache:'no-store',signal:AbortSignal.timeout(180000)});const payload=await response.json().catch(()=>({})) as {chart_points?:Array<Record<string,unknown>>;heatmap_points?:Array<Record<string,unknown>>;error?:string};if(!response.ok)throw new Error(payload.error||`Could not load ${domain} data.`);return Array.isArray(payload.chart_points)?payload.chart_points:Array.isArray(payload.heatmap_points)?payload.heatmap_points:[];};try{const [pitching,hitting]=await Promise.all([fetchDomain('pitching'),fetchDomain('hitting')]);const results=evaluateFlagRules(rules,{pitching,hitting});await Promise.all(results.map(async(result)=>{const rule=rules.find((r)=>r.id===result.ruleId);if(!rule?.notificationsEnabled||!rule.createdByUserId||!(await claimFlagNotification(rule.id,result.player,result.sessionDate)))return;const direction=result.change>=0?'increased':'decreased';const detail=`${result.player}: ${result.metric.replaceAll('_',' ')} ${direction} by ${Math.abs(result.change).toFixed(2)} (${Math.abs(result.changePercent).toFixed(1)}%) versus the ${rule.baselineDays}-day session baseline.`;await createNotificationsForUsers({recipientUserIds:[rule.createdByUserId],eventType:'metric_flag',title:`Flag: ${rule.name}`,detail,path:'/portal/dashboard?suite=flags',playerName:result.player});await sendPushNotificationToUsers({userIds:[rule.createdByUserId],title:`Flag: ${rule.name}`,body:detail,data:{path:'/(tabs)/dashboard/flags'}});}));return NextResponse.json({results,rules,generatedAt:new Date().toISOString()});}catch(error){return NextResponse.json({error:error instanceof Error?error.message:'Could not evaluate flags.'},{status:500});}}
