export type MetricGlossaryEntry = {
  name: string;
  aliases: string[];
  definition: string;
  domain: 'pitching' | 'hitting' | 'both';
  typicalTableMode: string;
};

export const METRICS_GLOSSARY: MetricGlossaryEntry[] = [
  {
    name: 'FPS%',
    aliases: ['fps', 'fps%', 'first pitch strike', 'first pitch strike%', 'firstpitchstrike'],
    definition: 'First-pitch strike percentage: how often the first pitch of a plate appearance is a strike.',
    domain: 'pitching',
    typicalTableMode: 'Results',
  },
  {
    name: 'BB%',
    aliases: ['bb', 'bb%', 'walk%', 'walk rate', 'walk percentage', 'bases on balls'],
    definition: 'Walk rate: the percentage of plate appearances that end in a walk.',
    domain: 'both',
    typicalTableMode: 'Results',
  },
  {
    name: 'K%',
    aliases: ['k', 'k%', 'k rate', 'strikeout%', 'strikeout rate', 'strikeout percentage', 'so%'],
    definition: 'Strikeout rate: the percentage of plate appearances that end in a strikeout.',
    domain: 'both',
    typicalTableMode: 'Results',
  },
  {
    name: 'PV/100',
    aliases: ['pv100', 'pv/100', 'pitch value', 'pitch value per 100'],
    definition: 'Pitch Value per 100 pitches: run value contributed by a pitch, normalized per 100 thrown.',
    domain: 'pitching',
    typicalTableMode: 'Results',
  },
  {
    name: 'RV/100',
    aliases: ['rv100', 'rv/100', 'run value', 'run value per 100'],
    definition: 'Run Value per 100 pitches: raw run value of outcomes, normalized per 100 thrown.',
    domain: 'pitching',
    typicalTableMode: 'Results',
  },
  {
    name: 'xWOBA',
    aliases: ['xwoba', 'expected woba', 'expected weighted on base average'],
    definition: 'Expected weighted on-base average: a quality-of-contact-based estimate of offensive value per plate appearance.',
    domain: 'both',
    typicalTableMode: 'Results',
  },
  {
    name: 'xBA',
    aliases: ['xba', 'expected batting average'],
    definition: 'Expected batting average based on quality of contact (exit velocity and launch angle).',
    domain: 'both',
    typicalTableMode: 'Results',
  },
  {
    name: 'xISO',
    aliases: ['xiso', 'expected iso', 'expected isolated power'],
    definition: 'Expected isolated power: expected extra-base-hit power based on quality of contact.',
    domain: 'both',
    typicalTableMode: 'Results',
  },
  {
    name: 'Barrel%',
    aliases: ['barrel', 'barrel%', 'barrel rate', 'barrel percentage'],
    definition: 'Barrel rate: percentage of batted balls hit with the ideal combination of exit velocity and launch angle for extra-base hits.',
    domain: 'hitting',
    typicalTableMode: 'Batted Ball Data',
  },
  {
    name: 'GoZoneSw%',
    aliases: ['gozonesw', 'gozonesw%', 'go zone swing', 'chase rate', 'chase%', 'out of zone swing'],
    definition: 'Swing rate on pitches outside the strike zone (a "chase rate" measure of plate discipline).',
    domain: 'both',
    typicalTableMode: 'Process',
  },
  {
    name: 'InZone%',
    aliases: ['inzone', 'inzone%', 'in zone percentage', 'zone rate'],
    definition: 'Percentage of pitches thrown/seen inside the strike zone.',
    domain: 'both',
    typicalTableMode: 'Process',
  },
  {
    name: 'Velo',
    aliases: ['velo', 'velocity', 'avg velo', 'average velocity', 'mph'],
    definition: 'Average pitch velocity (mph) for the selected pitch type or arsenal.',
    domain: 'pitching',
    typicalTableMode: 'Stuff',
  },
  {
    name: 'Max',
    aliases: ['max velo', 'max velocity', 'top velo', 'top speed'],
    definition: 'Maximum recorded pitch velocity (mph) for the selected pitch type or arsenal.',
    domain: 'pitching',
    typicalTableMode: 'Stuff',
  },
  {
    name: 'E+A%',
    aliases: ['e+a', 'e+a%', 'early and ahead', 'ahead in count'],
    definition: '"Early and Ahead" percentage: how often the pitcher gets ahead in the count early.',
    domain: 'pitching',
    typicalTableMode: 'Results',
  },
  {
    name: 'Whiff%',
    aliases: ['whiff', 'whiff%', 'whiff rate', 'swing and miss', 'swinging strike rate'],
    definition: 'Whiff rate: percentage of swings that result in a miss.',
    domain: 'both',
    typicalTableMode: 'Process',
  },
  {
    name: 'CSW%',
    aliases: ['csw', 'csw%', 'called strikes plus whiffs'],
    definition: 'Called Strike plus Whiff percentage: percentage of total pitches that are either called strikes or swinging strikes.',
    domain: 'pitching',
    typicalTableMode: 'Process',
  },
  {
    name: 'IVB',
    aliases: ['ivb', 'induced vertical break', 'vertical break', 'ride'],
    definition: 'Induced Vertical Break: the vertical movement of a pitch attributable to spin (excluding gravity).',
    domain: 'pitching',
    typicalTableMode: 'Stuff',
  },
  {
    name: 'HB',
    aliases: ['hb', 'horizontal break', 'horizontal movement', 'run'],
    definition: 'Horizontal Break: the horizontal (side-to-side) movement of a pitch.',
    domain: 'pitching',
    typicalTableMode: 'Stuff',
  },
  {
    name: 'Spin',
    aliases: ['spin', 'rpm', 'spin rate'],
    definition: 'Spin rate of the pitch, measured in revolutions per minute (RPM).',
    domain: 'pitching',
    typicalTableMode: 'Stuff',
  },
  {
    name: 'Ext',
    aliases: ['ext', 'extension', 'release extension'],
    definition: 'Extension: how far in front of the pitching rubber the pitcher releases the ball.',
    domain: 'pitching',
    typicalTableMode: 'Stuff',
  },
  {
    name: 'Stuff+',
    aliases: ['stuff+', 'stuffplus', 'stuff plus'],
    definition: 'Stuff+: a composite pitch-quality grade based on velocity, movement, and release characteristics (100 = league average).',
    domain: 'pitching',
    typicalTableMode: 'Stuff',
  },
  {
    name: 'QP+',
    aliases: ['qp+', 'qpplus', 'qp plus', 'quality pitch plus'],
    definition: 'Quality Pitch Plus: a composite grade combining stuff and result quality for a pitch (100 = league average).',
    domain: 'pitching',
    typicalTableMode: 'Stuff',
  },
  {
    name: 'Ctrl+',
    aliases: ['ctrl+', 'control+', 'ctrlplus', 'control plus'],
    definition: 'Control+: a composite command/control grade for a pitcher (100 = league average).',
    domain: 'pitching',
    typicalTableMode: 'Stuff',
  },
  {
    name: 'Pitching+',
    aliases: ['pitching+', 'pitchingplus', 'pitching plus'],
    definition: 'Pitching+: an overall composite pitching grade combining stuff, control, and results (100 = league average).',
    domain: 'pitching',
    typicalTableMode: 'Stuff',
  },
  {
    name: 'Usage',
    aliases: ['usage', 'usage%', 'usage percentage', 'pitch mix', 'pitch usage'],
    definition: 'Usage rate: percentage of total pitches thrown that are a given pitch type.',
    domain: 'pitching',
    typicalTableMode: 'Usage',
  },
  {
    name: 'BF',
    aliases: ['bf', 'batters faced'],
    definition: 'Batters Faced: total number of batters a pitcher has faced (used as a sample-size threshold for leaderboards).',
    domain: 'pitching',
    typicalTableMode: 'Results',
  },
  {
    name: 'PA',
    aliases: ['pa', 'plate appearances'],
    definition: 'Plate Appearances: total number of times a hitter has batted (used as a sample-size threshold for leaderboards).',
    domain: 'hitting',
    typicalTableMode: 'Results',
  },
  {
    name: 'GB%',
    aliases: ['gb%', 'ground ball rate', 'groundball%', 'ground ball percentage'],
    definition: 'Ground ball rate: percentage of batted balls hit on the ground.',
    domain: 'both',
    typicalTableMode: 'Batted Ball Data',
  },
  {
    name: 'Exit Velo',
    aliases: ['exit velo', 'exit velocity', 'ev'],
    definition: 'Average exit velocity of batted balls off the bat (mph).',
    domain: 'both',
    typicalTableMode: 'Batted Ball Data',
  },
  {
    name: 'SIERA',
    aliases: ['siera'],
    definition: 'Skill-Interactive ERA: a defense-independent ERA estimator based on strikeout, walk, and batted-ball rates.',
    domain: 'pitching',
    typicalTableMode: 'Results',
  },
  {
    name: 'Contact%',
    aliases: ['contact%', 'contact rate'],
    definition: 'Contact rate: percentage of swings that make contact with the ball.',
    domain: 'both',
    typicalTableMode: 'Process',
  },
  {
    name: 'Swing%',
    aliases: ['swing%', 'swing rate'],
    definition: 'Swing rate: percentage of pitches seen that the batter swings at.',
    domain: 'both',
    typicalTableMode: 'Process',
  },
];
