'use client';
import { useEffect,useRef,useState } from 'react';
type Player={playerId:number;fullName:string};
type Session={id:number;title:string;sessionType:string;sourceKind:'audio'|'video';status:string;summaryBullets:string[];transcriptText:string;playerVisible:boolean;keepAudio:boolean;audioAvailable:boolean;playerIds:number[];playerNames:string[];createdAt:string;errorMessage:string|null};
const TYPES=['Bullpen','Game/Postgame','Meeting','Assessment','Rehab','General'];
export default function AiSessionsClient(){
 const [sessions,setSessions]=useState<Session[]>([]),[players,setPlayers]=useState<Player[]>([]),[file,setFile]=useState<File|null>(null),[title,setTitle]=useState(''),[sessionType,setSessionType]=useState('Bullpen'),[playerIds,setPlayerIds]=useState<number[]>([]),[playerVisible,setPlayerVisible]=useState(false),[keepAudio,setKeepAudio]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[recording,setRecording]=useState(false),[openId,setOpenId]=useState<number|null>(null);const recorder=useRef<MediaRecorder|null>(null);const chunks=useRef<Blob[]>([]);
 async function load(){const [a,b]=await Promise.all([fetch('/api/ai/sessions',{cache:'no-store'}),fetch('/api/admin/clients',{cache:'no-store'})]);const ap=await a.json(),bp=await b.json();setSessions(ap.sessions??[]);setPlayers(bp.players??[]);}
 useEffect(()=>{void load();},[]);
 async function startRecording(){try{const stream=await navigator.mediaDevices.getUserMedia({audio:true});const r=new MediaRecorder(stream);chunks.current=[];r.ondataavailable=(e)=>{if(e.data.size)chunks.current.push(e.data);};r.onstop=()=>{const blob=new Blob(chunks.current,{type:r.mimeType||'audio/webm'});setFile(new File([blob],`session-${Date.now()}.webm`,{type:blob.type}));stream.getTracks().forEach((track)=>track.stop());setRecording(false);};recorder.current=r;r.start(1000);setRecording(true);setMessage('Recording…');}catch{setMessage('Microphone access was not available.');}}
 function stopRecording(){recorder.current?.stop();setMessage('Recording ready to process.');}
 async function create(){if(!file||!title.trim())return setMessage('Add a title and recording first.');setBusy(true);setMessage('Uploading recording…');try{const presign=await fetch('/api/ai/sessions/presign',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({fileName:file.name,contentType:file.type,sizeBytes:file.size})});const p=await presign.json();if(!presign.ok)throw new Error(p.error);const upload=await fetch(p.uploadUrl,{method:'PUT',headers:{'Content-Type':p.contentType},body:file});if(!upload.ok)throw new Error('Upload failed.');const created=await fetch('/api/ai/sessions',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({title,sessionType,playerIds,playerVisible,keepAudio,r2Key:p.r2Key,fileName:file.name,contentType:p.contentType,sizeBytes:file.size,sourceKind:file.type.startsWith('video/')?'video':'audio'})});const c=await created.json();if(!created.ok)throw new Error(c.error);setMessage('Transcribing and creating summary…');const processed=await fetch(`/api/ai/sessions/${c.id}/process`,{method:'POST'});const result=await processed.json();if(!processed.ok)throw new Error(result.error);setFile(null);setTitle('');setPlayerIds([]);setMessage('Transcript and summary are ready.');await load();setOpenId(c.id);}catch(error){setMessage(error instanceof Error?error.message:'Processing failed.');await load();}finally{setBusy(false);}}
 async function save(item:Session){setBusy(true);try{const response=await fetch('/api/ai/sessions',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(item)});const p=await response.json();if(!response.ok)throw new Error(p.error);setMessage('Session saved.');await load();}catch(error){setMessage(error instanceof Error?error.message:'Save failed.');}finally{setBusy(false);}}
 async function remove(id:number){if(!confirm('Delete this transcript, summary, and retained audio?'))return;await fetch(`/api/ai/sessions?id=${id}`,{method:'DELETE'});await load();}
 async function retry(id:number){setBusy(true);setMessage('Retrying transcription…');try{const r=await fetch(`/api/ai/sessions/${id}/process`,{method:'POST'});const p=await r.json();if(!r.ok)throw new Error(p.error);setMessage('Transcript and summary are ready.');await load();}catch(error){setMessage(error instanceof Error?error.message:'Retry failed.');await load();}finally{setBusy(false);}}
 return <div style={{display:'grid',gap:16}}>
  <section className="portal-panel" style={{padding:16,display:'grid',gap:12}}><h3 style={{margin:0}}>New AI Session</h3><div className="portal-form-grid"><label>Title<input value={title} onChange={(e)=>setTitle(e.target.value)} placeholder="Bullpen with Logan" /></label><label>Session type<select value={sessionType} onChange={(e)=>setSessionType(e.target.value)}>{TYPES.map((x)=><option key={x}>{x}</option>)}</select></label></div>
  <div style={{display:'flex',gap:8,flexWrap:'wrap'}}><button className={recording?'btn btn-danger':'btn btn-ghost'} onClick={recording?stopRecording:startRecording} disabled={busy}>{recording?'Stop recording':'Record audio'}</button><label className="btn btn-ghost" style={{cursor:'pointer'}}>Upload audio or video<input type="file" accept="audio/*,video/*" hidden onChange={(e)=>setFile(e.target.files?.[0]??null)} /></label>{file?<span className="portal-muted-text">{file.name} · {(file.size/1024/1024).toFixed(1)} MB</span>:null}</div>
  <label>Associate players<select multiple value={playerIds.map(String)} onChange={(e)=>setPlayerIds(Array.from(e.target.selectedOptions).map((o)=>Number(o.value)))} style={{minHeight:110}}>{players.map((p)=><option key={p.playerId} value={p.playerId}>{p.fullName}</option>)}</select></label>
  <div style={{display:'flex',gap:18,flexWrap:'wrap'}}><label><input type="checkbox" checked={playerVisible} onChange={(e)=>setPlayerVisible(e.target.checked)} /> Player visible</label><label><input type="checkbox" checked={keepAudio} onChange={(e)=>setKeepAudio(e.target.checked)} /> Keep audio beyond 30 days</label></div><button className="btn btn-primary" onClick={()=>void create()} disabled={busy||recording}>{busy?'Processing…':'Create transcript & summary'}</button>{message?<p className="portal-muted-text" style={{margin:0}}>{message}</p>:null}</section>
  <section style={{display:'grid',gap:10}}><h3 style={{margin:0}}>Session Library</h3>{sessions.length===0?<p className="portal-muted-text">No AI sessions yet.</p>:sessions.map((item)=><article className="portal-panel" key={item.id} style={{padding:14}}><button type="button" onClick={()=>setOpenId(openId===item.id?null:item.id)} style={{all:'unset',cursor:'pointer',display:'grid',gap:4,width:'100%'}}><strong>{item.title}</strong><span className="portal-muted-text">{item.sessionType} · {new Date(item.createdAt).toLocaleString()} · {item.playerNames.join(', ')||'Unassigned'} · {item.status}</span></button>{openId===item.id?<SessionEditor item={item} busy={busy} onSave={save} onDelete={remove} onRetry={retry}/>:null}</article>)}</section>
 </div>;
}
function SessionEditor({item,busy,onSave,onDelete,onRetry}:{item:Session;busy:boolean;onSave:(item:Session)=>void;onDelete:(id:number)=>void;onRetry:(id:number)=>void}){const [draft,setDraft]=useState(item);return <div style={{display:'grid',gap:10,marginTop:14}}>{draft.errorMessage?<p className="auth-error">{draft.errorMessage}</p>:null}{draft.status==='failed'?<button className="btn btn-ghost" disabled={busy} onClick={()=>onRetry(draft.id)}>Retry transcription</button>:null}{draft.audioAvailable?<audio controls preload="metadata" src={`/api/ai/sessions/${draft.id}/audio`} style={{width:'100%'}} />:null}<label>Summary bullets<textarea rows={7} value={draft.summaryBullets.map((x)=>`• ${x}`).join('\n')} onChange={(e)=>setDraft({...draft,summaryBullets:e.target.value.split('\n').map((x)=>x.replace(/^\s*[•*-]\s*/, '').trim()).filter(Boolean)})} /></label><label>Full transcript<textarea rows={14} value={draft.transcriptText} onChange={(e)=>setDraft({...draft,transcriptText:e.target.value})} /></label><div style={{display:'flex',gap:14}}><label><input type="checkbox" checked={draft.playerVisible} onChange={(e)=>setDraft({...draft,playerVisible:e.target.checked})}/> Player visible</label><label><input type="checkbox" checked={draft.keepAudio} onChange={(e)=>setDraft({...draft,keepAudio:e.target.checked})}/> Keep audio</label></div><div style={{display:'flex',gap:8}}><button className="btn btn-primary" disabled={busy} onClick={()=>onSave(draft)}>Save edits</button><button className="btn btn-danger" disabled={busy} onClick={()=>onDelete(draft.id)}>Delete</button></div></div>;}
