import { NextResponse } from 'next/server';
import { requireAiAccess } from '../../../../lib/ai-access';
import { createAiSession, deleteAiSession, editAiSession, listAiSessions } from '../../../../lib/ai-workspace-db';
import { deleteObjectFromR2 } from '../../../../lib/biomechanics-storage';

export async function GET(request:Request){const access=await requireAiAccess(request);if(!access.ok)return NextResponse.json({error:access.error},{status:access.status});const url=new URL(request.url);const requested=Number(url.searchParams.get('playerId')??0)||undefined;const playerId=access.role==='player'?(access.playerId??undefined):requested;return NextResponse.json({sessions:await listAiSessions({organizationId:access.organizationId,playerId,includeStaffOnly:access.role!=='player'})});}
export async function POST(request:Request){const access=await requireAiAccess(request,true);if(!access.ok)return NextResponse.json({error:access.error},{status:access.status});const b=await request.json().catch(()=>({})) as Record<string,unknown>;const title=String(b.title??'').trim();const r2Key=String(b.r2Key??'');const sourceKind=b.sourceKind==='video'?'video':'audio';if(!title||!r2Key.startsWith(`ai-sessions/org-${access.organizationId}/uploads/`))return NextResponse.json({error:'A title and completed recording upload are required.'},{status:400});const id=await createAiSession({organizationId:access.organizationId,userId:access.userId,title,sessionType:String(b.sessionType??'General').trim()||'General',sourceKind,r2Key,fileName:String(b.fileName??'recording'),contentType:String(b.contentType??'application/octet-stream'),sizeBytes:Number(b.sizeBytes??0),playerIds:Array.isArray(b.playerIds)?b.playerIds.map(Number).filter((x)=>x>0):[],playerVisible:Boolean(b.playerVisible),keepAudio:Boolean(b.keepAudio)});return NextResponse.json({id},{status:201});}
export async function PATCH(request:Request){const access=await requireAiAccess(request,true);if(!access.ok)return NextResponse.json({error:access.error},{status:access.status});const b=await request.json().catch(()=>({})) as Record<string,unknown>;const id=Number(b.id??0);const title=String(b.title??'').trim();if(!id||!title)return NextResponse.json({error:'Session and title are required.'},{status:400});await editAiSession({id,organizationId:access.organizationId,title,sessionType:String(b.sessionType??'General'),summaryBullets:Array.isArray(b.summaryBullets)?b.summaryBullets.map(String).filter(Boolean).slice(0,20):[],transcriptText:String(b.transcriptText??''),playerVisible:Boolean(b.playerVisible),keepAudio:Boolean(b.keepAudio)});return NextResponse.json({ok:true});}
export async function DELETE(request:Request){const access=await requireAiAccess(request,true);if(!access.ok)return NextResponse.json({error:access.error},{status:access.status});const id=Number(new URL(request.url).searchParams.get('id')??0);if(!id)return NextResponse.json({error:'Session id required.'},{status:400});const keys=await deleteAiSession(id,access.organizationId);await Promise.all(keys.map((key)=>deleteObjectFromR2(key).catch(()=>{})));return NextResponse.json({ok:true});}
