export const LEAGUE_TEAM_NAME_BY_CODE: Record<string, string> = {
    "USABASEBALL": "USA Baseball",
    "ABI_WIL": "Abilene Christian University",
    "AIR_FOR": "United States Air Force Academy",
    "AKR_ZIP": "University of Akron",
    "ALA_CRI": "University of Alabama",
    "ALA_HOR": "Alabama State University",
    "ALA_LIO": "University of North Alabama",
    "APP_MOU": "Appalachian State University",
    "AND_TRO": "Anderson University",
    "ARI_SUN": "Arizona State University",
    "ARI_WIL": "University of Arizona",
    "ARK_RAZ": "University of Arkansas",
    "ARL_MAV": "The University of Texas at Arlington",
    "ASU_RED": "Arkansas State University",
    "AUB_UNI": "Auburn University at Montgomery",
    "AUB_TIG": "Auburn University",
    "AVE_MAR": "Ave Maria University",
    "ALA_ANM": "Alabama A&M University",
    "ARK_TEC": "Arkansas Tech University",
    "AUS_GOV": "Austin Peay State University",
    "AZU_PAC": "Azusa Pacific University",
    "BEL_ABB": "Belmont Abbey College",
    "BEL_KNI": "Bellarmine University",
    "BIN_BEA": "Binghamton University",
    "BET_WIL": "Bethune-Cookman University",
    "BRO_BEA": "Brown University",
    "BUT_BUL": "Butler University",
    "BAY_BEA": "Baylor University",
    "BEL_BRU": "Belmont University",
    "BGS_FAL": "Bowling Green State University",
    "BAL_CAR": "Ball State University",
    "BOC_EAG": "Boston College",
    "BRY_BUL": "Bryant University",
    "BUC_BIS": "Bucknell University",
    "BYU_COU": "Brigham Young University",
    "CAL_LAN": "California Baptist University",
    "CAN_GRI": "Canisius University",
    "CAR_EAG": "Carson-Newman University",
    "CAL_FUL": "California State University, Fullerton",
    "CAL_HIG": "University of California, Riverside",
    "CAL_ANT": "University of California, Irvine",
    "CAL_POL": "California Polytechnic State University, San Luis Obispo",
    "CAT_IND": "Catawba College",
    "CEN_BEA": "University of Central Arkansas",
    "CEN_MIC": "Central Michigan University",
    "CLE_TIG": "Clemson University",
    "CIN_BEA": "University of Cincinnati",
    "CIT_BUL": "The Citadel",
    "COA_CHA": "Coastal Carolina University",
    "COL_LION": "Columbia University",
    "COR_BRE": "Cornell University",
    "CRE_BLU": "Creighton University",
    "CSD_TRI": "University of California, San Diego",
    "CSU_BAK": "California State University, Bakersfield",
    "COW_COU": "College of the Canyons",
    "CUM_PAT": "University of the Cumberlands",
    "CYP_CHR": "Cypress College",
    "CED_UNI": "Cedarville University",
    "DAL_PAT": "Dallas Baptist University",
    "DAR_GRE": "Dartmouth College",
    "DAV_UNI": "Davidson College",
    "DAV_WIL": "University of California, Davis",
    "DAY_FLY": "University of Dayton",
    "DEL_BLU": "University of Delaware",
    "DEL_STA": "Delaware State University",
    "DIC_RED": "Dickinson College",
    "DUK_BLU": "Duke University",
    "ECU_PIR": "East Carolina University",
    "EKU_COL": "Eastern Kentucky University",
    "EIU_PAN": "Eastern Illinois University",
    "ELO_PHO": "Elon University",
    "EMO_HEN": "Emory & Henry University",
    "EMU_EAG": "Eastern Michigan University",
    "ETS_BUC": "East Tennessee State University",
    "EVA_ACE": "University of Evansville",
    "FDU_KNI": "Fairleigh Dickinson University",
    "FAU_OWL": "Florida Atlantic University",
    "FGCU": "Florida Gulf Coast University",
    "FLA_GAT": "University of Florida",
    "FLO_RAT": "Florida A&M University",
    "FLO_PAN": "Florida International University",
    "FLO_SEM": "Florida State University",
    "FRE_BUL": "California State University, Fresno",
    "FRE_PAC": "Fresno Pacific University",
    "FOR_RAM": "Fordham University",
    "GAR_RUN": "Gardner-Webb University",
    "GEO_BUL": "University of Georgia",
    "GEO_EAG": "Georgia Southern University",
    "GEO_FOX": "George Fox University",
    "GEO_GWI": "George Washington University",
    "GEO_HOY": "Georgetown University",
    "GEO_PAT": "George Mason University",
    "GEO_PAN": "Georgia State University",
    "GRA_CAN": "Grand Canyon University",
    "GRA_TIG": "Grambling State University",
    "GIT_YEL": "Georgia Institute of Technology",
    "GON_BUL": "Gonzaga University",
    "HAR_CRI": "Harvard University",
    "HAW_HIL": "University of Hawai'i at Hilo",
    "HAW_PAC": "Hawai'i Pacific University",
    "HAW_WAR": "University of Hawaii",
    "HBU_HUS": "Houston Christian University",
    "HOF_PRI": "Hofstra University",
    "HIG_PAN": "High Point University",
    "HOL_CRU": "College of the Holy Cross",
    "HOO_COL": "Hood College",
    "HOU_COU": "University of Houston",
    "HUT_COM": "Hutchinson Community College",
    "ILL_TEC": "Illinois Institute of Technology",
    "ILL_ILL": "University of Illinois Urbana-Champaign",
    "ILL_RED": "Illinois State University",
    "ILL_WES": "Illinois Wesleyan University",
    "IND_TEC": "Indiana Tech",
    "IND_SYC": "Indiana State University",
    "ION_GAE": "Iona University",
    "IOW_CEN": "Iowa Central Community College",
    "IOW_HAW": "University of Iowa",
    "IU": "Indiana University Bloomington",
    "JAC_TIG": "Jackson College",
    "JAC_GAM": "Jackson State University",
    "JMU_DUK": "James Madison University",
    "KAN_JAY": "University of Kansas",
    "KS_GF": "Kent State University",
    "KAN_WIL": "Kansas State University",
    "KEN_WIL": "University of Kentucky",
    "KEN_OWL": "Kennesaw State University",
    "KIN_UNI": "King University",
    "LAF_LEP": "Lafayette College",
    "LAK_ERI21": "Lake Erie College",
    "LEE_UNI": "Lee University",
    "LEN_BEA": "Lenoir-Rhyne University",
    "LEH_MOU": "Lehigh University",
    "LIB_FLA": "Liberty University",
    "LIN_MEM": "Lincoln Memorial University",
    "LIN_UNI": "Lindenwood University",
    "LIP_BIS": "Lipscomb University",
    "LIT_TRO": "University of Arkansas at Little Rock",
    "LOC_HAV": "Lock Haven University",
    "LON_LAN": "Longwood University",
    "LON_DIR": "Long Beach State University",
    "LOU_BUL": "Louisiana Tech University",
    "LOU_CAJ": "University of Louisiana, Lafayette",
    "LOU_CAR": "University of Louisiana Monroe",
    "LOY_LIO": "Loyola Marymount University",
    "LOY_UNI": "Loyola University Chicago",
    "LSU_TIG": "Louisiana State University",
    "LYC_COL": "Lycoming College",
    "MAI_BLA": "University of Maine",
    "MAD_UNI": "Madonna University",
    "MAN_JAS": "Manhattan University",
    "MCN_COW": "McNeese State University",
    "MAR_TER": "University of Maryland",
    "MAR_LIO": "Mars Hill University",
    "MER_BEA": "Mercer University",
    "MER_UNI": "Mercyhurst University",
    "MEX_LOB": "University of New Mexico",
    "MIA_HUR": "University of Miami",
    "MIC_SPA": "Michigan State University",
    "MIC_WOL": "University of Michigan",
    "MIA_RED": "Miami University",
    "MID_GEO": "Middle Georgia State University",
    "MIN_GOL": "University of Minnesota Twin Cities",
    "MIS_DEL": "Mississippi Delta Community College",
    "MIS_GUL": "Mississippi Gulf Coast Community College",
    "MIS_BEA": "Missouri State University",
    "MIZ_TIG": "University of Missouri",
    "MON_HAW": "Monmouth University",
    "MOR_EAG": "Morehead State University",
    "MSM_MTN": "Mount St. Mary's University",
    "MSU_BDG": "Mississippi State University",
    "MTSU_BLU": "Middle Tennessee State University",
    "MUR_RAC": "Murray State University",
    "NAV_COL": "Navarro College",
    "NAV_MID": "United States Naval Academy",
    "NCB": "North Carolina A&T State University",
    "NEB": "University of Nebraska Lincoln",
    "NU": "University of Nebraska",
    "NEV_WOL": "University of Nevada, Reno",
    "NIC_COL": "Nicholls State University",
    "NIA_EAG": "Niagara University",
    "NJI_HIG": "New Jersey Institute of Technology",
    "NMS_AGG": "New Mexico State University",
    "NEW_WLV": "Newberry University",
    "NOR_AGG": "North Carolina A&T State University",
    "NOR_DEM": "Northwestern State University",
    "NOR_BIS": "North Dakota State University",
    "NOR_GRE": "North Greenville University",
    "NOR_HUS": "Northeastern University",
    "NOR_TAR": "University of North Carolina at Chapel Hill",
    "NOV_SOU": "Nova Southeastern University",
    "NIU_HUS": "Northern Illinois University",
    "NOT_IRI": "University of Notre Dame",
    "ODE_COL": "Odessa College",
    "OHI_BOB": "Ohio University",
    "OAK_GOL": "Oakland University",
    "OKL_CPR": "Oklahoma State University",
    "OKL_COW": "Oklahoma State University",
    "OKL_SOO": "University of Oklahoma",
    "OKL_WES": "Oklahoma Wesleyan University",
    "OLD_MON": "Old Dominion University",
    "OLE_REB": "University of Mississippi",
    "ORA_GOL": "Oral Roberts University",
    "ORE_BEA": "Oregon State University",
    "ORE_DUC": "University of Oregon",
    "OUR_LAD": "Our Lady of the Lake University",
    "PAC_TIG": "University of the Pacific",
    "PAC_LUT": "Pacific Lutheran University",
    "PAR_JUN": "Paris Junior College",
    "PEA_RIV": "Pearl River Community College",
    "PEN_NIT": "Pennsylvania State University",
    "PSU": "Penn State University",
    "PEN_QUA": "University of Pennsylvania",
    "PEP_WAV": "Pepperdine University",
    "PIT_PAN": "University of Pittsburgh",
    "POI_LOM": "Point Loma Nazarene University",
    "POR_PIL": "University of Portland",
    "PRA_PAN": "Prairie View A&M University",
    "PRE_BLH": "Presbyterian College",
    "PRI_TIG": "Princeton University",
    "PUR_BOI": "Purdue University",
    "QUI_HAW": "Quincy University",
    "QUI_BOB": "Quinnipiac University",
    "QUN_RYL": "Queens University of Charlotte",
    "RAD_HIG": "Radford University",
    "REI_UNI": "Reinhardt University",
    "RHO_RAM": "University of Rhode Island",
    "RID_BRO": "Rider University",
    "RIC_OWL": "Rice University",
    "RIC_SPI": "University of Richmond",
    "RUT_SCA": "Rutgers University New Brunswick",
    "SAC_HOR": "California State University, Sacramento",
    "SAL_REG": "Salve Regina University",
    "SAL_JAG": "University of South Alabama",
    "SAM_BEA": "Sam Houston State University",
    "SAM_BUL": "Samford University",
    "SAN_AZT": "San Diego State University",
    "SAN_DON": "University of San Diego",
    "SAN_GAU": "University of California, Santa Barbara",
    "SAN_JAC": "San Jacinto College",
    "SAN_TOR": "University of San Diego",
    "SBU_SEA": "Stony Brook University",
    "SEA_RED": "Seattle University",
    "SET_HIL": "Seton Hill University",
    "SET_PIR": "Seton Hall University",
    "SIE_HEI": "Siena Heights University",
    "SIE_SAI": "Siena College",
    "SIU_SAL": "Southern Illinois University Carbondale",
    "SLC_CCB": "Salt Lake Community College",
    "SLU_BILL": "Saint Louis University",
    "SOU_GAM": "University of South Carolina",
    "SOU_JAC": "South Dakota State University",
    "SOU_JAG": "Southern University",
    "SOU_LIO": "Southeastern Louisiana University",
    "SOU_MIS": "University of Southern Mississippi",
    "SOU_ORE": "Southern Oregon University",
    "SOU_RED": "Southeast Missouri State University",
    "SOU_TRO": "University of Southern California",
    "SOU_WES": "Southern Wesleyan University",
    "STB_BON": "St. Bonaventure University",
    "STJ_HAW": "Saint Joseph's University",
    "STJ_RED": "St. John's University",
    "STM_GAE": "Saint Mary's College of California",
    "STM_RAT": "St. Mary's University",
    "STU_BOB": "St. Thomas University",
    "TCU_HFG": "Texas Christian University",
    "TAM_SPA": "University of Tampa",
    "TAR_TEX": "Tarleton State University",
    "TEN_TEC": "Tennessee Technological University",
    "TEN_WES": "Tennessee Wesleyan University",
    "TEN_VOL": "University of Tennessee",
    "TNU": "Trevecca Nazarene University",
    "TEX_A&M": "Texas A&M University",
    "TEX_AGG": "Texas A&M University",
    "TEX_BOB": "Texas State University",
    "TEX_ISL": "Texas A&M University-Corpus Christi",
    "TEX_LON": "The University of Texas at Austin",
    "TEX_RAI": "Texas Tech University",
    "TEX_TIG": "Texas Southern University",
    "THO_MOR": "Thomas More University",
    "TJC_APA": "Tyler Junior College",
    "TOL_ROC": "University of Toledo",
    "TOU_COL": "Tougaloo College",
    "TOW_TIG": "Towson University",
    "TRE_VAL": "Trevecca Nazarene University",
    "TRI_UNI": "Trinity University",
    "TRO_TRJ": "Troy University",
    "TRU_MCC": "Truett McConnell University",
    "TUF_UNI": "Tufts University",
    "TUL_GRE": "Tulane University",
    "TUS_PIO": "Tusculum University",
    "TUS_TUS": "Tuskegee University",
    "UAB_BLA": "The University of Alabama at Birmingham",
    "UCO_HUS": "University of Connecticut",
    "UCF_KNI": "University of Central Florida",
    "UCLA": "University of California, Los Angeles",
    "UIC_FLA": "University of Illinois Chicago",
    "ULM_WAR": "University of Louisiana Monroe",
    "UNC_PEM": "The University of North Carolina at Pembroke",
    "UNC_SEA": "University of North Carolina Wilmington",
    "UNC_SPA": "The University of North Carolina at Greensboro",
    "UNL_REB": "University of Nevada, Las Vegas",
    "UMA_BOS": "University of Massachusetts Boston",
    "UNI_BRI": "University of Bridgeport",
    "UMA_AMH": "University of Massachusetts Amherst",
    "UMBC_RET": "University of Maryland, Baltimore County",
    "UNM": "University of New Mexico",
    "UNO_MAV": "University of Nebraska Omaha",
    "USC_BEA": "University of South Carolina Beaufort",
    "USC_PAC": "University of South Carolina Aiken",
    "USC_UPS": "University of South Carolina Upstate",
    "USF_BUL": "University of South Florida",
    "UTM_SKY": "University of Tennessee at Martin",
    "UTS_ROA": "The University of Texas at San Antonio",
    "UTA_UTE": "University of Utah",
    "UTR_VAQ": "The University of Texas Rio Grande Valley",
    "UWM_PAN": "University of Wisconsin-Milwaukee",
    "VAL_BLA": "Valdosta State University",
    "VAL_CRU": "Valparaiso University",
    "VAN_COM": "Vanderbilt University",
    "VCU_RAM": "Virginia Commonwealth University",
    "VIL_WIL": "Villanova University",
    "VIR_CAV": "University of Virginia",
    "VIR_KEY": "Virginia Military Institute",
    "VIR_TEC": "Virginia Tech",
    "WAB_VAL": "Wabash Valley College",
    "WAG_SEA": "Wagner College",
    "WAK_DEA": "Wake Forest University",
    "WAR_UNI1": "Warner University",
    "WAS_COU": "Washington State University",
    "WAS_HUS": "University of Washington",
    "WAS_S": "Washington University",
    "WCC": "West Coast Conference",
    "WHI_PIR": "Whitworth University",
    "WIC_SHO": "Wichita State University",
    "WOF_TER": "Wofford College",
    "WIN_EAG": "Winthrop University",
    "WIN_BUL": "Wingate University",
    "WES_HIL": "Western Kentucky University",
    "WIU_LEA": "Western Illinois University",
    "WRI_RAI": "Wright State University",
    "XAV_MUS": "Xavier University",
    "WM_TRI": "William & Mary",
    "YAL_BUL": "Yale University",
    "YSU_PEN": "Youngstown State University",
    "WAR_GAT": "Wareham Gatmen",
    "BOU_BRA": "Bourne Braves",
    "BRE_WHI": "Brewster Whitecaps",
    "CHA_ANG": "Chatham Anglers",
    "COT_KET": "Cotuit Kettleers",
    "FAL_COM": "Falmouth Commodores",
    "HAR_MAR": "Harwich Mariners",
    "HYA_HAR": "Hyannis Harbor Hawks",
    "ORL_FIR": "Orleans Firebirds",
    "YAR_RED": "Y-D Red Sox",
    "OCE_STA6": "Ocean State Waves",
    "NSH_N": "North Shore Navigators",
    "UPP_VAL": "Upper Valley Nighthawks",
    "SAN_MAI": "Sanford Mainers",
    "VAL_BLU": "Valley Blue Sox",
    "MYS_SCH": "Mystic Schooners",
    "NOR_ADA": "North Adams SteepleCats",
    "VER_MOU": "Vermont Mountaineers",
    "BRI_B": "Bristol Blues",
    "NEW_GUL": "Newport Gulls",
    "KEE_SWA": "Keene Swamp Bats",
    "MAR_VIN": "Martha's Vineyard Sharks",
    "DAN_WES": "Danbury Westerners",
    "BAD_BIG1": "Badlands Big Sticks",
    "BIS_MAR": "Bismarck Larks",
    "DUL_H": "Duluth Huskies",
    "EAU_C": "Eau Claire Express",
    "LAC_L": "La Crosse Loggers",
    "LAK_C": "Lakeshore Chinooks",
    "MAD_M": "Madison Mallards",
    "MAN_MOO": "Mankato MoonDogs",
    "MIN_HOT": "Minot Hot Tots",
    "MIN_M": "Minnesota Mud Puppies",
    "NWL_BC": "Battle Creek Battle Jacks",
    "NWL_FDL": "Fond du Lac Dock Spiders",
    "NWL_GBB": "Green Bay Rockers",
    "NWL_GRE": "Green Bay Rockers",
    "NWL_GRE1": "Green Bay Rockers",
    "NWL_KG": "Kalamazoo Growlers",
    "NWL_KKF": "Kenosha Kingfish",
    "NWL_SCR": "St. Cloud Rox",
    "NWL_WB": "Waterloo Bucks",
    "NWL_WRR": "Wisconsin Rapids Rafters",
    "RIC_FLY5": "Richmond Flying Mummies",
    "ROC_HON": "Rochester Honkers",
    "ROC_RIV": "Rockford Rivets",
    "ROY_OAK": "Royal Oak Leprechauns",
    "THU_BAY": "Thunder Bay Border Cats",
    "TRA_SPI": "Traverse City Pit Spitters",
    "WAU_WOO": "Wausau Woodchucks",
    "WIL_MAR": "Willmar Stingers",
    // West Coast League
    "BEL_BEL": "Bellingham Bells",
    "PTA_LEF": "Port Angeles Lefties",
    "COR_KNI": "Corvallis Knights",
    "WWA_SWE": "Walla Walla Sweets",
    "SPR_DRI": "Springfield Drifters",
    "KAM_NOR": "Kamloops NorthPaws",
    "WEN_APP": "Wenatchee AppleSox",
    "POR_PIC": "Portland Pickles",
    "KEL_FAL": "Kelowna Falcons",
    "BEN_ELK": "Bend Elks",
    "YAK_PIP": "Yakima Valley Pippins",
    "VIC_HAR": "Victoria HarbourCats",
    "MAR_BER": "Marion Berries",
    "NAN_NIG": "Nanaimo NightOwls",
    "EDM_RIV": "Edmonton Riverhawks",
};
